pull_request_rules:
  - name: vm4 review-thread native ruleset only 250925
    conditions:
      - base = main
      - title = VM4 RT101 NATIVEONLY GO 250925
    actions:
      merge:
        method: merge
